### ISSUE TITLE
Create a homepage for storybook

### ISSUE THREAD

**Issue by Loque-** [UKHomeOffice/govuk-react#317]
It would be useful to have a homepage for storybook that introduces the project and provides context for new visitors as well as helping people to get to the components they may want to access quickly.

**Comment by stevesims** [comment]
I’m wondering if this could be the readme file?

**Comment by gavinorland** [comment]
The way to approach this seems to be to get Storybook itself to order its stories alphabetically rather than randomly, and then we could make the first one the one containing the readme.

I have accordingly made [a commit](https://github.com/UKHomeOffice/govuk-react/commit/ec5d922cedfafb63f9517bfc578b9fc5dea2d513) to achieve this, so far to no effect! If anyone else would like to take a look at this, feel free. If not I'll take another look at it soon.

**Comment by Loque-** [comment]
I don't think this is the case, check the demos here: 

https://storybook.js.org/examples/

The first example has a component called `Welcome` at the top... 

https://building.coursera.org/coursera-ui/?selectedKind=Welcome&selectedStory=to%20Storybook&full=0&addons=0&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by gavinorland** [comment]
That's handy - I'll try to see how they're doing that! Still good if we can get the order less random too, I think.

**Comment by gavinorland** [comment]
Fixed via #374.
