### ISSUE TITLE
Use of <strong> for bold text is not accessibility-friendly

### ISSUE THREAD

**Issue by Joe-Brady** [UKHomeOffice/govuk-react#338]
I have noticed that most (possibly all) cases where text is supposed to be **bold**, this is achieved through a `<strong>` tag. This includes the markdown implementation and some components where the text is always bold.

Screen readers interpret `<strong>` tags as not just bold, but extremely emphasised, so the volume increases dramatically when the reader encounters these tags.

This detracts from the experience and user-friendliness for accessibility users, so I have been told that this is considered a bad practice.

Bold styling should be applied instead with CSS alone.

**Comment by Loque-** [comment]
Nice catch Joe, what would be a suitable semantic replacement tag considering accessibility? Do you also have a reference for the volume increasing when a screenreader encounters the strong tag as I can't find anything with a quick search.

There may be an argument that it is by design also, surely if something is in strong, it should have it's volume increased also? The GDS recommends against using strong and emphasis in general; https://govuk-elements.herokuapp.com/typography/#typography-body-copy

**Comment by Loque-** [comment]
My initial reflection might be that the implementation of `<strong />` is correct, but it should be used sparsely, if, at all, on implementations.

**Comment by Joe-Brady** [comment]
I agree that it's the correct implementation perhaps for markdown etc... are there any components where it is a purely visual bolding?

E.g. WarningText, but I appreciate that's a 'warning' so it might be ok keeping it as <strong>

In which case I'd be happy to close!

**Comment by Loque-** [comment]
I think it is a really valuable observation and we should add a comment to the paragraph component so users of the library are aware.

**Comment by accessiblewebuk** [comment]
As far as I know <strong> still isn't supported by most screenreaders - but happy to be corrected if that has changed. 

@Joe-Brady "are there any components where it is a purely visual bolding?" why would anything need to be made bold just visually? If it is bold it is for emphasis and screen reader users need to know if something is emphasised (whether through a semantic way or through a text indication of some sort, or indeed an icon with appropriate alternative text).
